Coursework
Ole-Leo/memorize-cardgame pull request #12
Opened 2022-05-26 21:22 UTC by Ole-Leo

### **Обязательное**
**GIT**

- [x]  Код игры храниться в GIT (GitHub).
- [x]  У проекта есть README файл с описанием проекта.

**Рабочее окружение**
В проекте настроено рабочее окружение и настроен единый стиль кодирования:

- [x]  Настроен линтер для JS/TS кода.
- [x]  Настроен линтер для CSS/SASS кода.
- [x]  Настроен prettier для форматирования кода.
- [x]  Запуск линтеров осуществляется перед созданием коммита автоматически.

**Игра**

- [x]  Верстка соответствует макету (HTML/CSS).
- [x] Реализована логика выбора уровня сложности.
- [x]  Реализована логика выбора и сравнения карточек.
- [x]  Реализована логика вывода результатов игры.
- [x]  Игра работает корректно.
____
### **Опциональное**
- [x]  В проект интегрирован TypeScript.
- [x]  Входные аргументы функций и методов объектов затипизированы.
- [x] В проекте не используется тип `any`.
- [x]  Запуск проверки типов осуществляется перед созданием коммита автоматически (с помощью husky).

2022-05-29 10:05 UTC, mrerberg requested changes

2022-05-29 10:05 UTC, mrerberg commented on scripts/win-screen.ts
> +  finalTime.textContent = window.application.finalTime as string;
Чтобы не использовать `as`, можно же String(window.application.finalTime)

2022-05-29 10:05 UTC, mrerberg commented on scripts/start-screen.ts
> +      const target = event.target as HTMLElement;
Зачем так много as? Это не везде оправдано и это по сути некий хак. Ты переопределяешь реальный тип на тот, что указан в as

2022-05-29 10:05 UTC, mrerberg commented on scripts/game-screen.ts
> +  const shuffledCards: cardExample = shuffle(cards);
`cardExample` тип должен писаться с большой буквы

2022-05-29 10:05 UTC, mrerberg commented on index.ts
> +interface gameApplication {
Типы/интерфейсы пишутся с большой буквы

2022-05-29 10:05 UTC, mrerberg commented on index.ts
> +  timers: number | undefined;
timers?: number;

2022-05-29 10:05 UTC, mrerberg commented on index.ts
> +window.application = window.application || {};
Лишняя строчка

2022-05-29 10:05 UTC, mrerberg commented on scripts/additional.ts
> +export type cardExample = {
Если это тип для 1 карты, зачем в конце []?

2022-05-29 19:14 UTC, Ole-Leo commented on index.ts
> +interface gameApplication {
исправила
- [x]  interface GameApplication

2022-05-29 19:14 UTC, Ole-Leo commented on index.ts
> +  timers: number | undefined;
А для чего делать таймер необязательным? Чтобы убрать вариант undefined?

2022-05-29 19:14 UTC, Ole-Leo commented on index.ts
> +window.application = window.application || {};
удалила

2022-05-29 19:14 UTC, Ole-Leo commented on scripts/additional.ts
> +export type cardExample = {
Вообще, это был типа как раз для массива, т.к., апример, для переменной 
```js
const shuffledCards = shuffle(cards);
```
Предлагалась такая типизация:
```js
const shuffledCards: {
    name: string;
    'front-img': string;
    'back-img': string;
}[]
```
Я поменяла название типа, чтобы было понятно, что это не для одной карты:
```js
type CardsArray = {
  name: string;
  'front-img': string;
  'back-img': string;
}[];
```

2022-05-29 19:14 UTC, Ole-Leo commented on scripts/game-screen.ts
> +  const shuffledCards: cardExample = shuffle(cards);
Поменяла название типа и сделала с большой буквы:
```js
type CardsArray = {
  name: string;
  'front-img': string;
  'back-img': string;
}[];
```

2022-05-29 19:14 UTC, Ole-Leo commented on scripts/start-screen.ts
> +      const target = event.target as HTMLElement;
Я нашла это, как один из примеров, как можно избежать везде типа "HTMLFormElement | null"
Как вариант могу написать везде так:
 ```js 
const startForm: HTMLFormElement = document.querySelector('.start-form')!;
```
Также, если я не указываю, что `const target = event.target as HTMLElement` в следующей строке мне выдаёт ошибку на свойство dataset: "Свойство "dataset" не существует в типе "EventTarget"", и тоже самое, когда есть свойство classList. Поэтому, думаю, что в таких случаях можно оставить as , либо предложи свой вариант)

2022-05-29 19:14 UTC, Ole-Leo commented on scripts/win-screen.ts
> +  finalTime.textContent = window.application.finalTime as string;
Вообще убрала тут as string

2022-05-30 07:14 UTC, mrerberg commented on scripts/start-screen.ts
> +      const target = event.target as HTMLElement;
```ts
const startForm = document.querySelector('.start-form');
```

Этого достаточно. У тебя только ts будет говорить, что данная переменная потенциально равна undefined, но можно добавить проверки на undefined

2022-05-30 07:15 UTC, mrerberg commented on index.ts
> +  timers: number | undefined;
Так добавив | undefined ты и так сделала его необязательным (опциональным)

2022-05-30 07:16 UTC, mrerberg commented on scripts/additional.ts
> +export type cardExample = {
Обычно разделяют типы на два

```ts
type Card = {
  name: string;
  'front-img': string;
  'back-img': string;
};

type Cards = Cart[];
```

2022-05-30 10:50 UTC, Ole-Leo commented on scripts/additional.ts
> +export type cardExample = {
О, круто! Спасибо, поменяла)

2022-05-30 10:51 UTC, Ole-Leo commented on scripts/start-screen.ts
> +      const target = event.target as HTMLElement;
В случае отсутствия "!", ts говорит, что "Возможно, объект равен null".
Можно, конечно, сделать проверку на null, но в данном случае очевидно, что данная переменная существует, поэтому, я всё-таки оставлю как есть)

2022-05-31 07:33 UTC, mrerberg requested changes

2022-05-31 07:33 UTC, mrerberg commented on scripts/start-screen.ts
> +  const startForm = document.querySelector('.start-form')!;
Лучше завязываться не на классы, а на дата атрибуты или id. Класс довольна переменная и изменяющаяся величина. На классе лучше не завязывать логику

2022-05-31 07:33 UTC, mrerberg commented on scripts/start-screen.ts
> +  const startForm = document.querySelector('.start-form')!;
Это про весь проект

2022-05-31 11:36 UTC, merged